# -*- coding: utf-8 -*-
"""Pyton - To-do List App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XZEA_d_JF530Mg_5kcQuQPXCcj4LjdjY
"""

# To-do List App

# Function to display task
def display_tasks(tasks):
    """Displays the current list of tasks."""
    if not tasks:
        print("Your to-do list is empty.")
    else:
        print("\nCurrent To-Do List:")
        for index, task in enumerate(tasks, start=1):
            print(f"{index}. {task}")

# Function to add task
def add_task(tasks):
    """Adds a new task to the to-do list."""
    task = input("Enter the task to add: ").strip()
    if task:
        tasks.append(task)
        print(f"Task '{task}' has been added.")
    else:
        print("Task cannot be empty.")

# Function to remove task
def remove_task(tasks):
    """Removes a task from the to-do list."""
    try:
        display_tasks(tasks)
        task_num = int(input("Enter the task number to remove: "))
        if 1 <= task_num <= len(tasks):
            removed_task = tasks.pop(task_num - 1)
            print(f"Task '{removed_task}' has been removed.")
        else:
            print("Invalid task number.")
    except ValueError:
        print("Please enter a valid number.")

# Function to update task
def update_task(tasks):
    """Updates an existing task in the to-do list."""
    try:
        display_tasks(tasks)
        task_num = int(input("Enter the task number to update: "))
        if 1 <= task_num <= len(tasks):
            new_task = input("Enter the new task description: ").strip()
            if new_task:
                tasks[task_num - 1] = new_task
                print(f"Task {task_num} has been updated to '{new_task}'.")
            else:
                print("Task description cannot be empty.")
        else:
            print("Invalid task number.")
    except ValueError:
        print("Please enter a valid number.")

# Main program
def main():
    """Main function to run the to-do list application."""
    tasks = []  # List to store tasks

    while True:
        print("\nTo-Do List Options:")
        print("1. View tasks")
        print("2. Add a task")
        print("3. Remove a task")
        print("4. Update a task")
        print("5. Exit")

        try:
            choice = int(input("Enter your choice: "))

            if choice == 1:
                display_tasks(tasks)
            elif choice == 2:
                add_task(tasks)
            elif choice == 3:
                remove_task(tasks)
            elif choice == 4:
                update_task(tasks)
            elif choice == 5:
                print("Exiting the To-Do List application. Goodbye!")
                break
            else:
                print("Please choose a valid option (1-5).")
        except ValueError:
            print("Invalid input. Please enter a number between 1 and 5.")

if __name__ == "__main__":
    main()
